version: "3"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./prisma/dev-db-data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"